import docsInteraction from './docs/docsInteraction'
import { VIM } from './main'
export default async function test() {
  const Q = VIM.CommandQueue
  Q.add({ command: docsInteraction.pasteText, params: { text: 'No\n\n' } })
  Q.add({ command: docsInteraction.toggleBold, params: [] })
  Q.add({ command: docsInteraction.pasteText, params: { text: 'Yes\n\n' } })
  Q.add({ command: docsInteraction.pasteText, params: { text: 'Yes\n\n' } })
  // Q.add({
  //   command: docsInteraction.pressKey,
  //   params: { key: 'b', opts: { ctrlKey: true, shiftKey: false, mac: GLOBALS.isMac } },
  // })
  // Q.add({ command: docsInteraction.toggleBold, params: [] })
  // Q.add({ command: docsInteraction.pasteText, params: { text: 'This should be bold' } })
  // VIM.CommandQueue.add({ command: docsInteraction.jumpTo, params: { target: 'h' } })
  // Q.add({ command: docsInteraction.pasteText('This should paste\n\n'), params: { _: 'This should paste\n\n' } })
  // Q.add({ command: docsInteraction.pasteText('This should paste\n\n'), params: { _: 'This should paste\n\n' } })
  // Q.add({ command: docsInteraction.toggleBold().pasteText('This text should be bold\n\n'), params: { _: 'This text should be bold\n\n' } })
  // Q.add({ command: docsInteraction.toggleBold().pasteText('This should not be bold\n\n'), params: { _: 'This should not be bold\n\n' } })
  // Q.add({ command: docsInteraction.toggleItalic().pasteText('This text should be Italic\n\n'), params: { _: 'This text should be Italic\n\n' } })
  // Q.add({ command: docsInteraction.togleItalic().pasteText('This should not be Italic\n\n'), params: { _: 'This should not be Italic\n\n' } })
  // Q.add({ command: docsInteraction.toggleUnderline().pasteText('This text should be Underline\n\n'), params: { _: 'This text should be Underline\n\n' } })
  // Q.add({ command: docsInteraction.toggleUnderline().pasteText('This should not be Underline\n\n'), params: { _: 'This should not be Underline\n\n' } })
  // Q.add({ command: docsInteraction.pickColor('red'), params: { _: 'red' } })
  // Q.add({ command: docsInteraction.pasteText('This text should be red\n\n'), params: { _: 'This text should be red\n\n' } })
  // Q.add({ command: docsInteraction.pickColor('green'), params: { _: 'green' } })
  // Q.add({ command: docsInteraction.pasteText('This text should be green\n\n'), params: { _: 'This text should be green\n\n' } })
  // Q.add({ command: docsInteraction.pickColor('black'), params: { _: 'black' } })
  // Q.add({ command: docsInteraction.pasteText('Back to black\n\n'), params: { _: 'Back to black\n\n' } })
  // Q.add({ command: docsInteraction.pickHighlight('red'), params: { _: 'red' } })
  // Q.add({ command: docsInteraction.pasteText('This text should be highlighted red\n\n'), params: { _: 'This text should be highlighted red\n\n' } })
  // Q.add({ command: docsInteraction.pickHighlight('green'), params: { _: 'green' } })
  // Q.add({ command: docsInteraction.pasteText('This text should be highlighted green\n\n'), params: { _: 'This text should be highlighted green\n\n' } })
  // Q.add({ command: docsInteraction.pickHighlight('blue'), params: { _: 'blue' } })
  // Q.add({ command: docsInteraction.pasteText('This text should be highlighted blue\n\n'), params: { _: 'This text should be highlighted blue\n\n' } })
  // Q.add({ command: docsInteraction.pickHighlight('none'), params: { _: 'none' } })
  // Q.add({ command: docsInteraction.pasteText('Back to black\n\n'), params: { _: 'Back to black\n\n' } })
  // Q.add({ command: docsInteraction.pasteText('1A2A3A4A5A6A7A8A9A10A'), params: { _: '1A2A3A4A5A6A7A8A9A10A' } })
  // Q.add({ command: docsInteraction.pressKey('ArrowLeft', { ctrlKey: true, shiftKey: false, mac: GLOBALS.isMac }), params: { _: 'ArrowLeft', { ctrlKey: true, shiftKey: false, mac: GLOBALS.isMac } } })
  // Q.add({ command: docsInteraction.jumpTo('A', 7), params: { _: 'A', 7 } })
  // Q.add({ command: docsInteraction.pasteText('|I was here|'), params: { _: '|I was here|' } })
  // Q.add({ command: docsInteraction.pressKey('ArrowRight', { ctrlKey: true, shiftKey: false, mac: GLOBALS.isMac }), params: { _: 'ArrowRight', { ctrlKey: true, shiftKey: false, mac: GLOBALS.isMac } } })
  // Q.add({ command: docsInteraction.pressKey('Enter', {}, 2), params: { _: 'Enter', {}, 2 } })
  // Q.add({ command: docsInteraction.pasteText('A10A98A7A6A5A4A3A2A1A OtherBloatText'), params: { _: 'A10A98A7A6A5A4A3A2A1A OtherBloatText' } })
  // Q.add({ command: docsInteraction.jumpTo('A', 5, false), params: { _: 'A', 5, false } })
  // Q.add({ command: docsInteraction.pasteText('|I was here|'), params: { _: '|I was here|' } })
  // Q.add({ command: docsInteraction.pressKey('ArrowRight', { ctrlKey: true, shiftKey: false, mac: GLOBALS.isMac }), params: { _: 'ArrowRight', { ctrlKey: true, shiftKey: false, mac: GLOBALS.isMac } } })
  // Q.add({ command: docsInteraction.pressKey('Enter', {}, 2), params: { _: 'Enter', {}, 2 } })
  // Q.add({ command: docsInteraction.pasteText('aaaaaAaaaaAaa'), params: { _: 'aaaaaAaaaaAaa' } })
  // Q.add({ command: docsInteraction.pressKey('ArrowLeft', { ctrlKey: true, shiftKey: false, mac: GLOBALS.isMac }), params: { _: 'ArrowLeft', { ctrlKey: true, shiftKey: false, mac: GLOBALS.isMac } } })
  // Q.add({ command: docsInteraction.jumpTo('A'), params: { _: 'A' } })
  // Q.add({ command: docsInteraction.pasteText('|I was here|'), params: { _: '|I was here|' } })
}
